# config.yaml
basic:
  parallelism_num: 1
  datalink_auth_config: "/home/user/GameLauncher/orcasim.json"
  orcasim_path: "/home/user/GameLauncher/OrcaStudio_2409.GameLauncher"
  level: "3c"
  levelorca: "3c_SH-F-002_0828_2_shijue"

connection:
  orcagym_address: "localhost:50051"
  agent_names: "openloong_gripper_2f85_fix_base_usda"
  pico_ports: "8001"

mode:
  run_mode: "augmentation"
  action_type: "joint_pos"

task:
  task_config: "a3c_task.yaml"
  dataset: "/home/user/kps/OrcaGym/examples/openpi/processed_datasets_tmp/combined_DualArmEnv_1_0_0_3C_guiji_SH-B-001_task_2025-08-26_14-26-05.hdf5"

advanced:
  record_length: 1200
  playback_mode: "random"
  rollout_times: 10
  augmented_noise: 0.005
  augmented_rounds: 20
  teleoperation_rounds: 100
  sample_range: 0
  realtime_playback: 'True'
  withvideo: 'True'
  index: 0
  sync_codec: 'False'
  useNvenc: 1
